### ISSUE TITLE
Error using JobFlow's cluster_status method

### ISSUE THREAD

**Issue by fblundun** [rslifka/elasticity#115]
```
TypeError (can't convert nil into an exact number):
    /home/vagrant/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/cluster_status.rb:23:in `at'
    /home/vagrant/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/cluster_status.rb:23:in `block in from_aws_data'
    /home/vagrant/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/cluster_status.rb:18:in `tap'
    /home/vagrant/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/cluster_status.rb:18:in `from_aws_data'
    /home/vagrant/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/job_flow.rb:153:in `cluster_status'
```

I think that `cluster_data['Status']['Timeline']['ReadyDateTime']` can be `nil` which causes `Time.at` to throw an exception [here](https://github.com/rslifka/elasticity/blob/master/lib/elasticity/cluster_status.rb#L23).

**Comment by fblundun** [comment]
Just looked at my copy of the file in `~/.rvm/gems/ruby-2.2.1/gems/elasticity-6.0.1/lib/elasticity/cluster_status.rb` as installed by Bundler and I see that the real problem is that it somehow doesn't have the latest version of the file:

```
module Elasticity

  class ClusterStatus

    attr_accessor :name
    attr_accessor :cluster_id
    attr_accessor :state
    attr_accessor :created_at
    attr_accessor :ready_at
    attr_accessor :ended_at
    attr_accessor :last_state_change_reason
    attr_accessor :master_public_dns_name
    attr_accessor :normalized_instance_hours

    # ClusterStatus is created via the results of the DescribeCluster API call
    def self.from_aws_data(cluster_data)
      cluster_data = cluster_data['Cluster']
      ClusterStatus.new.tap do |c|
        c.name = cluster_data['Name']
        c.cluster_id = cluster_data['Id']
        c.state = cluster_data['Status']['State']
        c.created_at = Time.at(cluster_data['Status']['Timeline']['CreationDateTime'])
        c.ready_at = Time.at(cluster_data['Status']['Timeline']['ReadyDateTime'])
        c.ended_at = Time.at(cluster_data['Status']['Timeline']['EndDateTime'])
        c.last_state_change_reason = cluster_data['Status']['StateChangeReason']['Code']
        c.master_public_dns_name = cluster_data['MasterPublicDnsName']
        c.normalized_instance_hours = cluster_data['NormalizedInstanceHours']
      end
    end

    # http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/ProcessingCycle.html
    def active?
      %w{RUNNING STARTING BOOTSTRAPPING WAITING SHUTTING_DOWN}.include?(@state)
    end

  end

end
```

Bundle claims it is installing version 6.0.1 but the gem I get doesn't seem to correspond to the latest revision of the repo.

**Comment by fblundun** [comment]
Hey @rslifka , we figured out that the version published on RubyGems corresponds to the v6.0.1 tag rather than master. Would it be possible to get a 6.0.2 released so we can use these latest changes?

Thanks!

**Comment by rslifka** [comment]
Yep, 6.0.2 released just now.  Sorry about that :smile:

**Comment by fblundun** [comment]
Thanks a lot @rslifka !
